### ISSUE TITLE
"Online Minutes Interval" - Doesn't logout automatically after set minutes

### ISSUE THREAD

**Issue by yaronle** [gigya/Magento-2#1]
**Description:**
The "Online Minutes Interval" was set (via the admin site) to 2 minutes.
Once tested, the site was not logged out after the 2 minutes has passed.

**Step To Reproduce:**
1) Navigate to the Magento site
2) Login as Admin
3) Open Stores -> Customers -> Customers Configuration
4) Set "Online Minutes Interval" to "2"
![image](https://cloud.githubusercontent.com/assets/11631352/14278627/52aca042-fb31-11e5-8275-0670f0ce508c.png)
5) Click "Save Config"
6) Logout of Admin and return to login screen
7) Login with regular user
8) Wait 2 minuted and click "F5" (Refresh page)

**Expected Results:**
The user is logged out of the session

**Actual Results:**
The user remains logged in

**Comment by shirlyleibovich** [comment]
Issue will be resolved in next release.
