### ISSUE TITLE
magento 2.4 and php 7.4 support

### ISSUE THREAD

**Issue by sivamind** [gigya/Magento-2#103]
Deprecated Functionality: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a
   ? b : (c ? d : e)` in /app/vendor/gigya/magento2-im/Helper/RetryGigyaSyncHelper.php on line 149

  Deprecated Functionality: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a
   ? b : (c ? d : e)` in /app/vendor/gigya/magento2-im/Controller/Raas/GigyaPost.php on line 525

**Comment by wgtgithub** [comment]
Knock, knock, hello?

**Comment by sivamind** [comment]
sorry i upgraded gigya now its working thank you
