### ISSUE TITLE
Error when run setup:di:compile - version 5.7.0

### ISSUE THREAD

**Issue by ducquywp92** [gigya/Magento-2#106]
Module version: 5.7.0.
Environment: Production/Develop
An error occurred when I try to run setup:di:compile.

`Errors during compilation:
	Gigya\GigyaIM\Logger\Logger
		Incompatible argument type: Required type: string. Actual type: \Gigya\GigyaIM\Logger\name; File: 
/app/app/code/Gigya/GigyaIM/Logger/Logger.php`

Class: Gigya\GigyaIM\Logger\Logger
Look like you are missing param type for $name in __contruct() function.
It should be **@param string $name** instead of **@param $name**.
Can you fix it asap?

**Comment by Ynhockey** [comment]
Done, sorry about that.
