### ISSUE TITLE
Magento 2.4.2 gigya login and register error

### ISSUE THREAD

**Issue by sivamind** [gigya/Magento-2#109]
Getting below error in gigya register from magento frontend
logger.ERROR: Gigya returned an error when validating the user. It is possible that there is a problem with the Gigya credentials configured on th
e site. Error details: {^M
  "callId": "d4b3d2ef9efd4ddb8a552c102c630a90",^M
  "errorCode": 405001,^M
  "errorDetails": "Endpoint not supported for global site",^M
  "errorMessage": "Invalid API method",^M
  "apiVersion": 2,^M
  "statusCode": 405,^M
  "statusReason": "Method Not Allowed",^M
  "time": "2021-03-09T05:13:02.401Z"^M
} [] []

**Comment by levistepanov** [comment]
The GConnector does not currently support using Global Site API Keys. When creating a site for use with Magento in the CDC Console, be sure to choose 'Local Data Center' in the Data Residency options.

**Comment by Ynhockey** [comment]
Hi Sivamind, just to make sure: how did you try to authenticate? User/secret authentication isn't supported on global sites, only private/public key pair.

**Comment by Ynhockey** [comment]
Closed with no response for a long time
