### ISSUE TITLE
Address not syncing with Magento 2 gigya

### ISSUE THREAD

**Issue by dhirajdanodeborn** [gigya/Magento-2#113]
We are using  Gigya 5.7.1  with Magento latest version 2.4.2
Gigya Login Registration working properly.. But Address not get Synced in Gigya console

1. Login in Magento
2. Created New Address from customer account.
3. Enable Offline Sync
4. Expecting Address should sync in Gigya Console but its not showing

Can you please confirm if this feature available in gigya

**Comment by Ynhockey** [comment]
Hi, can you please paste your field mapping config here? If it's something you don't want to disclose, please open a ticket with support and it will be looked at asap. Thanks!

**Comment by dhirajdanodeborn** [comment]
Hello

we are not using filed mapping json. Its default setting.
Do we need to use filed mapping json for address mapping.

Can you share th sample filed mapping json.

**Comment by dhirajdanodeborn** [comment]
Hello Ynhockey

Any updates on this.

**Comment by Ynhockey** [comment]
Address sync has been added in 5.8.0, please open a new issue if something isn't working there. Thanks!
