### ISSUE TITLE
Unable to save settings. Error: Permission denied.

### ISSUE THREAD

**Issue by molinainat** [gigya/Magento-2#116]
When trying to save general configuration, get the error:

Failed to connect to Gigya API. Unable to save settings. Error: Permission denied.

Magento EE 2.3.4-p2

**Comment by levistepanov** [comment]
Not a whole lot of information here, but if you are trying to save via a gigya API, you need to have a SAP Customer Data Cloud account.

**Comment by molinainat** [comment]
My apologies, we do have an account and were using Gigya_IM version 5.4.0. We are trying to upgrade the module to version 5.7.1 and ran into this error when trying to save the credentials in the new configuration fields.

**Comment by Ynhockey** [comment]
Hi Molinainat,

Since this might be an account permission issue, it might be best to open a ticket with support so that we can check the specific account, or the specific call ID where you get the error.

However, in general: one of the new features in versions 5.6.0 and later is support for the JWT-based authentication. Please make sure that if you're using the old say (user/secret), this is the selected method in your configuration (and conversely, if using key pair then the key pair auth is selected).

In addition, if you go to Advanced and turn on debug mode, you may be able to see more details for the error in var/log/gigya.log (if you would like to share it with us, please open a ticket with support).

**Comment by molinainat** [comment]
The account credentials are working as expected, the frontend login is possible using gigya profile. I didn't get any useful information from the log. I traced the error with xdebug and found:
 `  "errorDetails": "Invalid namespace &#39;socialize&#39; or method &#39;getProvidersConfig&#39; or you do not have the required permissions to call it. "`
In file app/code/Gigya/GigyaIM/Plugin/Config/Model/Config.php:91, I commented this:
`$this->gigyaMageHelper->getGigyaApiHelper()->sendApiCall(
                            'socialize.getProvidersConfig',
                            []
                        );`
and added "return true;"
Result:
` try {
                    $this->validateSettings($settings, $scopeType, $scopeCode);

                    $this->gigyaMageHelper->setGigyaSettings($scopeType, $scopeCode, $settings);
                    $gigyaApiHelper = $this->gigyaMageHelper->getGigyaApiHelper();

                    if ($gigyaApiHelper === false) {
                        throw new LocalizedException(__("Bad settings. Unable to save."));
                    } else {
                        /*$this->gigyaMageHelper->getGigyaApiHelper()->sendApiCall(
                            'socialize.getProvidersConfig',
                            []
                        );*/
                        return true;
                    }
                }`
Would you approve this to solve the saving configuration issue? So far I've been able to save and use the gigya login as expected. Please let me know of any other approach to avoid "Invalid namespace &#39;socialize&#39; or method &#39;getProvidersConfig&#39; or you do not have the required permissions to call it.", considering that the credentials are valid and working as expected.

**Comment by molinainat** [comment]
Steps to reproduce:

1. Go to Admin: Stores > Configuration > Gigya Identity Management > General
2. Save Config

Result:
Failed to connect to Gigya API. Unable to save settings. Error: Permission denied.

Expected:
You saved the configuration.

**Comment by molinainat** [comment]
PR: https://github.com/gigya/Magento-2/pull/117

**Comment by Ynhockey** [comment]
Hi Molinainat,

Thank you for the great effort put into this! Unfortunately we can't disable the basic authentication check for everyone, otherwise customers won't know if their credentials are valid.

I am investigating why an authenticated user might not have permissions to call this endpoint, but if you could open a ticket with your specific details and attach the call ID where you get this error, it would help immensely.

Thanks!

**Comment by molinainat** [comment]
Hi @Ynhockey, thank you for reviewing it. I double checked the old module and instead of using "socialize.getProvidersConfig" it uses 
```
->sendApiCall("accounts.getSchema", ["filter" => 'full'])
```
I tried applying those params but got the same error:
```
{
  "errorMessage": "Permission denied",
  "errorDetails": "Invalid namespace &#39;socialize&#39; or method &#39;getProvidersConfig&#39; or you do not have the required permissions to call it. ",
  "statusCode": 403,
  "errorCode": 403007,
  "statusReason": "Forbidden",
  "callId": "57098c460b074d55bf550652b4c3ee09",
  "time": "2021-11-17T16:39:51.507Z"
}
```
I modified the PR and applied the old method "accounts.getSchema" instead of returning true, and it worked, which means the issue was delimited to the new method.

Returning true would also work, as this line(83): $this->validateSettings($settings, $scopeType, $scopeCode) validates the API params and sets them to the $gigyaMageHelper, which later generates the $gigyaApiHelper. On line 88, it checks if the helper was generated successfully, meaning if the settings to save are valid. If it returns false, then it throws an exception "Bad settings. Unable to save". But if it returns something else than 'false', it means the API params are valid. However, I replaced the 'return true' from the previous commit, with:
```
$gigyaApiHelper->sendApiCall("accounts.getSchema", []);
```
And updated the PR. Kindly help to review and let me know if that approach is valid.

**Comment by Ynhockey** [comment]
Hi, I have looked further into it and can now confirm that getProvidersConfig is always present in the admin group for each partner. In other words, if a user does not have permissions to call this endpoint, it means they don't have full permissions to their site. The validation failure here is therefore not a bug, rather it's proof that the system works as intended.

accounts.getSchema is less good for validation, and it was therefore changed.

The correct fix for this is to grant the necessary permissions to your application in Gigya's admin console. If you need assistance with this, please open a support ticket and we should be able to resolve this shortly.

Note that if the application doesn't have full permissions to your site, it's possible that certain other endpoints won't work either, and you might not understand why – so I definitely suggest looking into it.

**Comment by molinainat** [comment]
Thank you so much for the support. I'm closing this ticket now
