### ISSUE TITLE
Not compatible with Latest monolog 

### ISSUE THREAD

**Issue by rajesh-xcube** [gigya/Magento-2#129]
Hi,

I am using Gigya for Magento 2.4.4 and it is using new Monolog. Getting below error while running setup upgrade command.

PHP Fatal error:  Declaration of Gigya\GigyaIM\Logger\Logger::addRecord($level, $message, array $context = Array) must be compatible with Monolog\Logger::addRecord(int $level, string $message, array $context = Array, ?Monolog\DateTimeImmutable $datetime = NULL): bool in /var/www/html/gigya-downloads/magento2-im/Logger/Logger.php on line 43

**Comment by samsteele** [comment]
Same issue, fix proposed in https://github.com/gigya/Magento-2/pull/130
