### ISSUE TITLE
Magento 2.4.5 compatibility

### ISSUE THREAD

**Issue by WaPoNe** [gigya/Magento-2#132]
Gigya Identity Management for Magento 2 requires

`"gigya/php-sdk": "~3.0",`

but PHP SDK for Gigya (_gigya/php-sdk_) requires

`"firebase/php-jwt": "^5.0",`

but in Magento 2.4.5 there is the **magento/services-connector** module that requires

`"firebase/php-jwt": "^6.0.0",`

and it installs "firebase/php-jwt" in version **v6.3.1**

so when I try to install **Gigya_GigyaIM**

`composer2 require gigya/magento2-im`

I receive these error messages:

```
  Problem 1
    - gigya/php-sdk 3.0 requires firebase/php-jwt ^5.2 -> found firebase/php-jwt[v5.2.0, ..., v5.5.1] but the package is fixed to v6.3.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - gigya/php-sdk 3.0.2 requires firebase/php-jwt ^5.0 -> found firebase/php-jwt[v5.0.0, ..., v5.5.1] but the package is fixed to v6.3.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - gigya/magento2-im 6.0.0 requires gigya/php-sdk ~3.0 -> satisfiable by gigya/php-sdk[3.0, 3.0.2].
    - Root composer.json requires gigya/magento2-im ^6.0 -> satisfiable by gigya/magento2-im[6.0.0].
```

**Comment by WaPoNe** [comment]
Hi @Ynhockey
I know that it is a dependency of the PHP SDK project; I also opened the issue in this project to underline the importance of a fast solution.

I thank you for your collaboration.

I'll wait for news.

**Comment by WaPoNe** [comment]
@Ynhockey I forgot to write you that yesterday I opened the issue in PHP SDK project: https://github.com/SAP/gigya-php-sdk/issues/24

**Comment by gianstraf** [comment]
Hi, we also meet the same problem on 2.4.5.
Is there some update  @Ynhockey ?

**Comment by Ynhockey** [comment]
Hi, there is now a PHP SDK branch that uses the updated Firebase JWT library (6.x), we're testing it + Magento with it, will keep everyone posted when it's done.

**Comment by WaPoNe** [comment]
@gianstraf for your information, they have released a new version of [Gigya PHP SDK](https://github.com/SAP/gigya-php-sdk/) including the [composer.json](https://github.com/SAP/gigya-php-sdk/blob/main/composer.json) updated with the right firebase/php-jwt version.
You can find it here: https://github.com/SAP/gigya-php-sdk/releases/tag/3.0.3
