### ISSUE TITLE
Connect magento2 and gigya using SAML.

### ISSUE THREAD

**Issue by pitbulk** [gigya/Magento-2#3]
Since [gigya is an Identity Provider that supports SAML](http://developers.gigya.com/display/GD/Gigya+as+SAML+IdP), in those environments where you are connecting apps with SAML, you can use this [SAML extension for Magento2](https://marketplace.magento.com/sixtomartin-onelogin-module-saml2.html) to connect with Magento2.

**Comment by shirlyleibovich** [comment]
Thanks for sharing.
